import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
        type: 'category',
        label: "Tutorial",
        items : [
          {
             type: 'autogenerated',
             dirName : 'tutorial-extras'
          }
        ]
    },
    'gated',
    'hello'
  ]
};

export default sidebars;
